### PR TITLE
Avoid new lines when base64 encoding values

### LINKED ISSUE #58: Manifest generation script fails with long API tokens
## General:

* [x] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [x] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

----

## Feature Requests:
* [x] Have you explained your rationale for why this feature is needed? 
* [x] Have you offered a proposed implementation/solution? 

----

## Bug Reporting
If Linode API token is longer than 58 characters base64 encoded string includes carriage returns which fails the deploy/generate-manifest.sh script

### Expected Behavior
deploy/generate-manifest.sh runs without errors and creates correctly the file ccm-linode.yaml

### Actual Behavior
The script fails with the following error:
sed: -e expression #1, char 104: unterminated `s' command

and the ccm-linode.yaml generated file is empty

### Steps to Reproduce the Problem

  1. export LINODE_API_TOKEN=some_long_string
  2. ./deploy/generate-manifest.sh $LINODE_API_TOKEN us-central
  3. The script fails

#### Additional Notes

----
 
For general help or discussion, join the [Kubernetes Slack team](https://kubernetes.slack.com/messages/CD4B15LUR/details/) channel `#linode`. To sign up, use the [Kubernetes Slack inviter](http://slack.kubernetes.io/).

The [Linode Community](https://www.linode.com/community/questions/) is a great place to get additional support.

### PR DESCRIPTION
**Pull request by nacef-labidi**
Closes #58 

### General:

* [x] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [x] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

### Pull Request Guidelines:

1. [x] Does your submission pass tests?
1. [ ] Have you added tests? 
1. [x] Are you addressing a single feature in this PR? 
1. [x] Are your commits atomic, addressing one change per commit?
1. [x] Are you following the conventions of the language? 
1. [ ] Have you saved your large formatting changes for a different PR, so we can focus on your work?
1. [x] Have you explained your rationale for why this feature is needed? 
1. [x] Have you linked your PR to an [open issue](https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/)

### CODE REVIEW

**Comment by asauber** [comment]
Hi, thanks for fix! Two things. 

Can you amend the commit to use your GitHub email address?

`-w0` is not a flag on the macOS (BSD) version of `base64`, where this script is often run, can you add some environment detection, similar to the following?

```
root@fdabd8ebb93f:/# BASE64FLAGS=""
root@fdabd8ebb93f:/# if [[ ! -z $(base64 --version | grep -i gnu) ]]; then BASE64FLAGS="-w0"; fi
root@fdabd8ebb93f:/# echo $BASE64FLAGS
-w0
```

**Comment by asauber** [comment]
You can be confident that flags of `""` are fine on macOS, it does not have this newline behavior by default:

```
macOS machine $ echo "reallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallylongline" | base64
cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5cmVhbGx5bG9uZ2xpbmUK
```

**Comment by nacef-labidi** [comment]
Thank you @asauber I will do the changes right away. I hope t gets merged soon, since I need this change to write a tutorial

**Comment by phillc** [comment]
Fixed in #63

**Pull request merged**
